### ISSUE TITLE
Add Physio object generation from BIDS structures

### ISSUE THREAD

**Issue by maestroque** [physiopy/physutils#3]
The end goal for this issue, would be to have a function that will generate a list of Physio objects, given a BIDS structure, along with an MRI data object. These could be encompassed in a multimodal Physio object in the future

**Comment by maestroque** [comment]
@m-miedema @me-pic I have a question regarding the commonly used BIDS layouts.

In the v1.9.0 BIDS spec, only the following column labels are specified. And they are not standardized, just recommended:

![image](https://github.com/physiopy/physutils/assets/74024609/853ec3b2-db2d-468e-b9a6-cb7236f54125)

In your experience, are those conventions followed? Specifically regarding the `trigger`. Because I would like to detect column names in order to create the appropriate object (either Physio or the MRI trigger data object). Also for example in some datasets ([example](https://github.com/OpenNeuroDatasets/ds003823/blob/main/sub-5001/ses-post/func/sub-5001_ses-post_task-emotionRegulation_physio.json)), it's not followed and the triggers are provided as `tr`. Other than those two what could other commonly used labels be, in order to be taken into account? For starters, I will just stick to the BIDS spec recommendations

**Comment by me-pic** [comment]
What about using something like what is implemented in [phys2bids](https://phys2bids.readthedocs.io/en/latest/cli.html) where there is an automatic search for the trigger channel based on the naming convention, but users could also have the possibility to specify the index of the trigger channel (see `chtrig` in phys2bids) ?

**Comment by maestroque** [comment]
This would aim to be used after `phys2bids` though, as BIDS output structures would be made into Physio objects to feed into peakdet or phys2denoise.
Would it seem like a good idea, to follow only the `phys2bids` naming convention for intra-physiopy package compatibility for starters? 
@me-pic

**Comment by m-miedema** [comment]
> In the v1.9.0 BIDS spec, only the following column labels are specified. And they are not standardized, just recommended:

These are indeed fairly uncommonly used, to my knowledge. We often use the column labels corresponding to our data acquisition device conventions. Our BIDS Extension Proposal(s) are aimed at reducing some of this ambiguity, but between backwards compatibility and optional depth of labelling, some will always remain.
